# Generated by Django 4.0.4 on 2022-05-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cartitem_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
